name: Modify File

on:
  workflow_call:
    inputs:
      file-path:
        required: true
        type: string
      target-string:
        required: true
        type: string
      replacer-string:
        required: true
        type: string

jobs:
  modify-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Modify file
        run: |
          sed -i 's/${{ inputs.target-string }}/${{ inputs.replacer-string }}/g' ${{ inputs.file-path }}
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Modify file"
          git push
