name: Modify File

on:
  workflow_call:
    inputs:
      file-path:
        required: true
        type: string

jobs:
  modify-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Modify file
        run: |
          sed -i 's/tag 1/tag 2/g' ${{ inputs.file-path }}
